<div class="header">
      <a href="/main.php"><i class="material-icons">home</i></a>
      <a href="/articles.php"><i class="material-icons">article</i></a>
      <a href="/products.php"><i class="material-icons">inventory</i></a>
      <a href="/permit.php"><i class="material-icons">photo</i></a>
      <a href="/index.php"><i class="material-icons">person_add</i></a>
      <a href="/admin.php"><i class="material-icons">admin_panel_settings</i></a>
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <nav class="nav">
    <ul>
    <li><a href="/main.php">Главная</a></li>
    <li><a href="/articles.php">Статьи</a></li>
    <li><a href="/products.php">Продукция</a></li>
    <li><a href="/permit.php">Галерея</a></li>
    <li><a href="/index.php">Регистрация</a></li>
    <li><a href="/admin.php">Администратор</a></li>
    <li><a target="_blank" href="/adminer.php">Базы Данных</a></li>
    </ul>
  </nav>
</div>
<!-- target="_blank"  -->
